development:
  adapter: postgresql
  database: earlymarket_development,
  username: daniel
  password: password
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: earlymarket_test,
  username: daniel
  password: password
  host: localhost
  port: 5432
  pool: 5